name: Flutter APK Build

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  build:
    name: Build Debug APK
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Set up Flutter stable (pin version to your local dev version)
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'
          channel: stable

      # 3️⃣ Clean previous build (kept to avoid cached errors)
      - name: Clean previous build
        run: flutter clean

      # 4️⃣ Pre-install Android SDK & NDK to avoid long downloads during build
      - name: Pre-install Android SDK & NDK
        run: |
          ANDROID_SDK_ROOT=/usr/local/lib/android/sdk
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "platforms;android-35" "ndk;27.0.12077973"

      # 5️⃣ Install dependencies
      - name: Get Flutter packages
        run: flutter pub get

      # 5.1️⃣ Generate app icons
      - name: Generate App Icons
        run: flutter pub run flutter_launcher_icons

      # 6️⃣ Build debug APK
      - name: Build Debug APK
        run: flutter build apk --debug --no-shrink --verbose

      # 7️⃣ Upload APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk

      # 8️⃣ Optional caching to speed up future builds
      - name: Cache Flutter pub packages
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-
      
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
